services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ADMIN_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    tmpfs:
      - /algod/empty
      - /algod/fast-catchup
    volumes:
      - algod:/algod/data
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
volumes:
  algod: