- name: Test Instance
  hosts: localhost
  tasks:
    - name: Ensure algorun exists
      stat:
        path: /usr/bin/algorun
      register: binpath
    - name: Fail missing binary
      fail:
        msg: "Must have algorun installed!"
      when: not binpath.stat.exists
    - name: Run installer
      command: algorun install
    - name: Run stop
      command: algorun stop
    - name: Run upgrade
      command: algorun upgrade
    - name: Run stop
      command: algorun stop
    - name: Run Start
      command: algorun start
      # TODO: start a private network, fund TUI account and run TUI integration