- name: Test Instance
  hosts: localhost
  tasks:
    - name: Ensure nodekit exists
      stat:
        path: /usr/bin/nodekit
      register: binpath
    - name: Fail missing binary
      fail:
        msg: "Must have nodekit installed!"
      when: not binpath.stat.exists
    - name: Run installer
      command: nodekit install
    - name: Run stop
      command: nodekit stop
    - name: Run upgrade
      command: nodekit upgrade
    - name: Run stop
      command: nodekit stop
    - name: Run Start
      command: nodekit start
      # TODO: start a private network, fund TUI account and run TUI integration