openapi: 3.0.1
info:
  contact:
    name: Algonode.io
    url: https://algonode.io/contact
  description: API endpoint for algod operations.
  title: Algod REST API.
  version: '3.16'
servers:
  - url: http://localhost:1337/
  - url: https://mainnet-api.algonode.cloud/
  - url: https://testnet-api.algonode.cloud/
  - url: https://betanet-api.algonode.cloud/
paths:
  /metrics:
    get:
      operationId: getMetrics
      responses:
        '200':
          content:
            application/text:
              schema:
                type: string
          description: Prometheus Exposition Endpoint
  /agreement/{hash}:
    get:
      operationId: getAgreementEvents
      parameters:
        - name: hash
          in: path
          description: 'Hash to lookup'
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
          description: Get Agreement events by Hash
  /ws:
    get:
      operationId: getWs
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
          description: Stuff
  /status:
    get:
      operationId: getStatus
      summary: Retrieve current status
      responses:
        '200':
          description: Respond with Status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
components:
  schemas:
    Status:
      type: object
      description: A status response
      properties:
        state:
          type: string
          description: The state of the node
        version:
          type: string
          description: Version reported by the node
        network:
          type: string
          description: Network ID
        voting:
          type: boolean
          description: If the network is voting on an upgrade
        needsUpdate:
          type: boolean
          description: If the node requires and update
        lastRound:
          type: number
          description: Last round the status has knowledge of