name: Code Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go get .

      - name: Check formatting
        run: |
          fmt_files=$(gofmt -l .)
          if [ -n "$fmt_files" ]; then
            echo "Go code is not formatted. Please run 'go fmt'."
            gofmt -d .
            exit 1
          fi

      - name: Tidy go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
          if [ $? -ne 0 ]; then
            echo "go.mod or go.sum is not tidy. Please run 'go mod tidy'."
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -o bin/nodekit *.go

      - name: Unit Tests
        run: make test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}