name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go get .

      - name: Check formatting
        run: |
          fmt_files=$(gofmt -l .)
          if [ -n "$fmt_files" ]; then
            echo "Go code is not formatted. Please run 'go fmt'."
            gofmt -d .
            exit 1
          fi

      - name: Tidy go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
          if [ $? -ne 0 ]; then
            echo "go.mod or go.sum is not tidy. Please run 'go mod tidy'."
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build .

      - name: Test with the Go CLI
        run: go test -v -coverprofile=coverage.txt ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

      - uses: fgrosse/go-coverage-report@v1.1.1
